apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: SSL_CERT_DIR
        value: "/var/run/fulcio"
  target:
    group: apps
    version: v1
    kind: Deployment
    namespace: fulcio-system
    name: fulcio-server
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/volumeMounts/-"
      value:
        mountPath: /docker-entrypoint-initdb.d/storage.sql
        name: mysql-storage-init
        subPath: storage.sql
    - op: add
      path: "/spec/template/spec/volumes/-"
      value:
        configMap:
          defaultMode: 420
          name: mysql-storage-init
        name: mysql-storage-init
  target:
    group: apps
    version: v1
    kind: Deployment
    namespace: trillian-system
    name: trillian-mysql
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/volumeMounts/-"
      value:
        mountPath: /docker-entrypoint-initdb.d/storage.sql
        name: mysql-storage-init
        subPath: storage.sql
    - op: add
      path: "/spec/template/spec/volumes/-"
      value:
        configMap:
          defaultMode: 420
          name: mysql-storage-init
        name: mysql-storage-init
  target:
    group: apps
    version: v1
    kind: Deployment
    namespace: trillian-system
    name: trillian-mysql
- patch: |-
    - op: add
      path: "/metadata/labels"
      value:
        openshift.io/cluster-monitoring: "true"
  target:
    version: v1
    kind: Namespace

helmGlobals:
  chartHome: ../../../rhtas/charts

helmCharts:
  - name: trusted-artifact-signer
    namespace: trusted-artifact-signer
    releaseName: trusted-artifact-signer
    valuesFile: values.yaml
