apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    - op: add
      path: "/metadata/labels"
      value:
        openshift.io/cluster-monitoring: "true"
  target:
    version: v1
    kind: Namespace
