---
{{- $appsSubdomain := required "Apps Subdomain is required" .Values.appsSubdomain -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.gitops.applicationName }}
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    namespace: {{ .Values.gitops.destinationNamespace }}
    server: {{ .Values.gitops.destinationServer }}
  project: {{ .Values.gitops.project }}
  source:
    repoURL: {{ .Values.gitops.source.url }}
    targetRevision: {{ .Values.gitops.source.branch }}
    path: {{ .Values.gitops.source.path }}
    kustomize:
      patches: {{ include "trusted-artifact-signer-gitops.patches" . | fromYamlArray | toYaml | nindent 8 }}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m 
