---
{{- $appsSubdomain := required "Apps Subdomain is required" .Values.appsSubdomain -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.gitops.applicationName }}
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    namespace: {{ .Values.gitops.destinationNamespace }}
    server: {{ .Values.gitops.destinationServer }}
  project: {{ .Values.gitops.project }}
  source:
    repoURL: {{ .Values.gitops.source.url }}
    targetRevision: {{ .Values.gitops.source.branch }}
    path: {{ .Values.gitops.source.path }}
    kustomize:
      patches:
        - patch: |-
            - op: replace
              path: /spec/rules/0/host
              value: fulcio.{{ $appsSubdomain }}
          target:
            kind: Ingress
            name: fulcio-server-http
        - patch: |-
            - op: replace
              path: /spec/rules/0/host
              value: rekor.{{ $appsSubdomain }}
          target:
            kind: Ingress
            name: rekor-server
        - patch: |-
            - op: replace
              path: /spec/rules/0/host
              value: tuf.{{ $appsSubdomain }}
          target:
            kind: Ingress
            name: tuf-server
        - patch: |-
            - op: add
              path: /spec/host
              value: tas-clients-trusted-artifact-signer-clientserver.{{ $appsSubdomain }}
          target:
            kind: Route
            name: tas-clients
        - patch: |-
            - op: replace
              path: /data/config.json
              value: |
                {
                    "OIDCIssuers": {
                      "https://keycloak-keycloak-system.{{ $appsSubdomain }}/auth/realms/sigstore": {
                          "ClientID": "sigstore",
                          "IssuerURL": "https://keycloak-keycloak-system.{{ $appsSubdomain }}/auth/realms/sigstore",
                          "Type": "email"
                        }
                    }
                }
          target:
            kind: ConfigMap
            name: fulcio-server-config
        - patch: |-
            - op: replace
              path: /spec/links/0/href
              value: https://tas-clients-trusted-artifact-signer-clientserver.{{ $appsSubdomain }}/clients/linux/cosign.gz
            - op: replace
              path: /spec/links/1/href
              value: https://tas-clients-trusted-artifact-signer-clientserver.{{ $appsSubdomain }}/clients/windows/cosign.gz
            - op: replace
              path: /spec/links/2/href
              value: https://tas-clients-trusted-artifact-signer-clientserver.{{ $appsSubdomain }}/clients/darwin/cosign.gz
          target:
            kind: ConsoleCLIDownload
            name: cosign
        - patch: |-
            - op: replace
              path: /spec/links/0/href
              value: https://tas-clients-trusted-artifact-signer-clientserver.{{ $appsSubdomain }}/clients/linux/gitsign.gz
            - op: replace
              path: /spec/links/1/href
              value: https://tas-clients-trusted-artifact-signer-clientserver.{{ $appsSubdomain }}/clients/darwin/gitsign.gz
            - op: replace
              path: /spec/links/2/href
              value: https://tas-clients-trusted-artifact-signer-clientserver.{{ $appsSubdomain }}/clients/windows/gitsign.gz
          target:
            kind: ConsoleCLIDownload
            name: gitsign
        - patch: |-
            - op: replace
              path: /spec/links/0/href
              value: https://tas-clients-trusted-artifact-signer-clientserver.{{ $appsSubdomain }}/clients/linux/rekor-cli.gz
            - op: replace
              path: /spec/links/1/href
              value: https://tas-clients-trusted-artifact-signer-clientserver.{{ $appsSubdomain }}/clients/darwin/rekor-cli.gz
            - op: replace
              path: /spec/links/2/href
              value: https://tas-clients-trusted-artifact-signer-clientserver.{{ $appsSubdomain }}/clients/windows/rekor-cli.gz
          target:
            kind: ConsoleCLIDownload
            name: rekor-cli
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m 
