apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: openshift-gitops
spec:
  destination:
    namespace: keycloak-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rhtas/keycloak/resources/base
    repoURL: https://github.com/sabre1041/sigstore-ocp
    targetRevision: declarative
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m 
