apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trusted-artifact-signer
  namespace: openshift-gitops
spec:
  destination:
    namespace: trusted-artifact-signer
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/overlays/ablock
    repoURL: https://github.com/sabre1041/sigstore-ocp
    targetRevision: declarative
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m 
