apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: SSL_CERT_DIR
        value: "/var/run/fulcio"
  target:
    group: apps
    version: v1
    kind: Deployment
    namespace: fulcio-system
    name: fulcio-server
